name: gradient_progress
description: A Gradient color support progressbar, fast way to have a beatiful gradient progress in your flutter app.
version: 0.1.0
author: ShaunRain <rainamie@gmail.com>
homepage: https://github.com/ShaunRain

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter